name: Continuous Integration
on: [push, pull_request]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate
      working-directory: ${{runner.workspace}}/target
      run: cmake ..
    - name: Build
      working-directory: ${{runner.workspace}}/target
      run: make
    - name: Test
      working-directory: ${{runner.workspace}}/target
      run: ctest --output-on-failure

